# Generated by Django 2.2.4 on 2020-11-26 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.IntegerField(blank=True, db_column='id', primary_key=True, serialize=False, unique=True)),
                ('account', models.TextField(blank=True)),
                ('password', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.IntegerField(blank=True, db_column='id', primary_key=True, serialize=False, unique=True)),
                ('brand', models.TextField(blank=True)),
                ('category', models.TextField(blank=True)),
                ('name', models.TextField(blank=True)),
                ('unitPrice', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'Product',
            },
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.IntegerField(blank=True, db_column='id', primary_key=True, serialize=False, unique=True)),
                ('name', models.TextField(blank=True)),
                ('unitPrice', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'Other',
            },
        ),
    ]
